#NAME: Milad Nourian
#EMAIL: miladnourian@ucla.edu
#ID: 004854226
FILES= main.c Makefile README

all:
	gcc -Wall -Wextra main.c -o lab1a
clean:
	rm -f lab1a lab1a-004854226.tar.gz
dist: all
	tar -czf lab1a-004854226.tar.gz $(FILES)
